os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
jobs:
  include:
    - stage: test
      if: branch = master
      script: ls;cd folder;ls;../flutter/bin/flutter test;
    - stage: format
      script: ./flutter/bin/flutter format -n --set-exit-if-changed folder/lib/*

cache:
  directories:
    - $HOME/.pub-cache
